package com.talkbridge.livetranslator.ui.theme

import androidx.compose.ui.graphics.Color

val primary = Color(0xFF0C2C54)
val onPrimary = Color(0xFFFFFFFF)
val primaryContainer = Color(0xFF1D3557)
val onPrimaryContainer = Color(0xFF879EC6)
val secondary = Color(0xFF296283)
val onSecondary = Color(0xFFFFFFFF)
val secondaryContainer = Color(0xFF457B9D)
val onSecondaryContainer = Color(0xFFFFFDFF)
val tertiary = Color(0xFFA7C9DC)
val onTertiary = Color(0xFFFFFFFF)
val tertiaryContainer = Color(0xFFA8DADC)
val onTertiaryContainer = Color(0xFF306163)
val error = Color(0xFFB7102A)
val onError = Color(0xFFFFFFFF)
val errorContainer = Color(0xFFDB313F)
val stopColor = Color(0xffed4c5c)
val onErrorContainer = Color(0xFFFFFBFF)
val background = Color(0xFFFAF9FC)
val onBackground = Color(0xFF1B1B1E)
val surface = Color(0xFFFCF8F8)
val onSurface = Color(0xFF1C1B1B)
val surfaceVariant = Color(0xFFE0E2EB)
val onSurfaceVariant = Color(0xFF44474E)
val outline = Color(0xFF74777F)
val outlineVariant = Color(0xFFC4C6CF)
val scrim = Color(0xFF000000)
val inverseSurface = Color(0xFF313030)
val inverseOnSurface = Color(0xFFF4F0EF)
val inversePrimary = Color(0xFFB0C7F1)
val surfaceDim = Color(0xFFDDD9D9)
val surfaceBright = Color(0xFFFCF8F8)
val surfaceContainerLowest = Color(0xFFFFFFFF)
val surfaceContainerLow = Color(0xFFF7F3F2)
val surfaceContainer = Color(0xFFF1EDEC)
val surfaceContainerHigh = Color(0xFFEBE7E7)
val surfaceContainerHighest = Color(0xFFE5E2E1)

//val primaryLight = Color(0xFF031F41)
//val onPrimaryLight = Color(0xFFFFFFFF)
//val primaryContainerLight = Color(0xFF1D3557)
//val onPrimaryContainerLight = Color(0xFF879EC6)
//val secondaryLight = Color(0xFF296283)
//val onSecondaryLight = Color(0xFFFFFFFF)
//val secondaryContainerLight = Color(0xFF457B9D)
//val onSecondaryContainerLight = Color(0xFFFFFDFF)
//val tertiaryLight = Color(0xFF356668)
//val onTertiaryLight = Color(0xFFFFFFFF)
//val tertiaryContainerLight = Color(0xFFA8DADC)
//val onTertiaryContainerLight = Color(0xFF306163)
//val errorLight = Color(0xFFB7102A)
//val onErrorLight = Color(0xFFFFFFFF)
//val errorContainerLight = Color(0xFFDB313F)
//val onErrorContainerLight = Color(0xFFFFFBFF)
//val backgroundLight = Color(0xFFFAF9FC)
//val onBackgroundLight = Color(0xFF1B1B1E)
//val surfaceLight = Color(0xFFFCF8F8)
//val onSurfaceLight = Color(0xFF1C1B1B)
//val surfaceVariantLight = Color(0xFFE0E2EB)
//val onSurfaceVariantLight = Color(0xFF44474E)
//val outlineLight = Color(0xFF74777F)
//val outlineVariantLight = Color(0xFFC4C6CF)
//val scrimLight = Color(0xFF000000)
//val inverseSurfaceLight = Color(0xFF313030)
//val inverseOnSurfaceLight = Color(0xFFF4F0EF)
//val inversePrimaryLight = Color(0xFFB0C7F1)
//val surfaceDimLight = Color(0xFFDDD9D9)
//val surfaceBrightLight = Color(0xFFFCF8F8)
//val surfaceContainerLowestLight = Color(0xFFFFFFFF)
//val surfaceContainerLowLight = Color(0xFFF7F3F2)
//val surfaceContainerLight = Color(0xFFF1EDEC)
//val surfaceContainerHighLight = Color(0xFFEBE7E7)
//val surfaceContainerHighestLight = Color(0xFFE5E2E1)
//
//val primaryDark = Color(0xFFB0C7F1)
//val onPrimaryDark = Color(0xFF183153)
//val primaryContainerDark = Color(0xFF1D3557)
//val onPrimaryContainerDark = Color(0xFF879EC6)
//val secondaryDark = Color(0xFF98CDF2)
//val onSecondaryDark = Color(0xFF00344C)
//val secondaryContainerDark = Color(0xFF457B9D)
//val onSecondaryContainerDark = Color(0xFFFFFDFF)
//val tertiaryDark = Color(0xFFC4F7F9)
//val onTertiaryDark = Color(0xFF003739)
//val tertiaryContainerDark = Color(0xFFA8DADC)
//val onTertiaryContainerDark = Color(0xFF306163)
//val errorDark = Color(0xFFFFB3B1)
//val onErrorDark = Color(0xFF680011)
//val errorContainerDark = Color(0xFFFF535B)
//val onErrorContainerDark = Color(0xFF2C0003)
//val backgroundDark = Color(0xFF121316)
//val onBackgroundDark = Color(0xFFE3E2E5)
//val surfaceDark = Color(0xFF141313)
//val onSurfaceDark = Color(0xFFE5E2E1)
//val surfaceVariantDark = Color(0xFF44474E)
//val onSurfaceVariantDark = Color(0xFFC4C6CF)
//val outlineDark = Color(0xFF8E9099)
//val outlineVariantDark = Color(0xFF44474E)
//val scrimDark = Color(0xFF000000)
//val inverseSurfaceDark = Color(0xFFE5E2E1)
//val inverseOnSurfaceDark = Color(0xFF313030)
//val inversePrimaryDark = Color(0xFF485F84)
//val surfaceDimDark = Color(0xFF141313)
//val surfaceBrightDark = Color(0xFF3A3939)
//val surfaceContainerLowestDark = Color(0xFF0E0E0E)
//val surfaceContainerLowDark = Color(0xFF1C1B1B)
//val surfaceContainerDark = Color(0xFF201F1F)
//val surfaceContainerHighDark = Color(0xFF2A2A2A)
//val surfaceContainerHighestDark = Color(0xFF353434)
//










